alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: thawhallow.voidtotable.com
  type: PRIMARY
  zone: thawhallow.voidtotable.com
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: thawhallow-wiki
    match:
      path:
        prefix: /
name: thawhallow-wiki
region: nyc
static_sites:
- github:
    branch: publish
    # this will deploy each time you push (recommended)
    deploy_on_push: true
    repo: voidtotable/thawhallow-wiki
  name: thawhallow-wiki
  output_dir: /workspace/publish
  source_dir: ./publish